-- ES Attendance – core: roster lookup, group scan, invites, attendance records.
-- UI lives in UI.lua, the shipped roster in RosterData.lua (generated by build_roster.py).
local ADDON, ns = ...
ESAttendance = ns

local ROSTER_HEADER = "ESROSTER"
local RECORD_HEADER = "ESA1"
local INVITE_INTERVAL = 0.6    -- s between invites
local INVITE_WAIT_MAX = 90     -- s to wait for the first accept / raid conversion
local GUILD_REFRESH_MIN = 10   -- s between C_GuildInfo.GuildRoster() requests

local CLASS_TOKEN = {
  ["death knight"] = "DEATHKNIGHT", ["demon hunter"] = "DEMONHUNTER", ["druid"] = "DRUID",
  ["evoker"] = "EVOKER", ["hunter"] = "HUNTER", ["mage"] = "MAGE", ["monk"] = "MONK",
  ["paladin"] = "PALADIN", ["priest"] = "PRIEST", ["rogue"] = "ROGUE", ["shaman"] = "SHAMAN",
  ["warlock"] = "WARLOCK", ["warrior"] = "WARRIOR",
}

ns.roster = {}          -- array of { name, class, role, chars = {..}, charClass = {..}, charRole = {..} }
ns.charToPlayer = {}    -- normalized char name -> player index
ns.present = {}         -- player index -> { char = "Name", unit = "raid3", online = bool }
ns.unknown = {}         -- group members not in the roster: { "Name", ... }
ns.guildOnline = {}     -- normalized char name -> "Name-Realm" of online guild members
ns.callbacks = {}

-- ---------------------------------------------------------------- helpers
local function trim(s) return (tostring(s or ""):gsub("^%s+", ""):gsub("%s+$", "")) end

--- "Name-Realm" -> "name" (lowercase, no realm). string.lower touches ASCII only, which is
--- fine: the roster sheet stores the same non-ASCII letters the players type in game.
function ns.NormName(name)
  name = tostring(name or "")
  local dash = name:find("-", 1, true)
  if dash then name = name:sub(1, dash - 1) end
  return name:lower()
end

function ns.ClassToken(cls)
  cls = trim(cls)
  if cls == "" then return nil end
  return CLASS_TOKEN[cls:lower()] or (cls:upper():gsub("%s", ""))
end

function ns.ClassColor(token)
  local c = token and (RAID_CLASS_COLORS and RAID_CLASS_COLORS[token])
  if not c and token and C_ClassColor then c = C_ClassColor.GetClassColor(token) end
  if c then return c.r, c.g, c.b end
  return 0.9, 0.9, 0.9
end

function ns.Print(msg)
  (DEFAULT_CHAT_FRAME or ChatFrame1):AddMessage("|cff3fd68aES Attendance:|r " .. tostring(msg))
end

function ns.Fire(event, ...)
  for _, cb in ipairs(ns.callbacks) do cb(event, ...) end
end

-- ---------------------------------------------------------------- roster
--- Import string, one player per line: Player;char;class;role[;char;class;role...]
--- First line: ESROSTER;<version>. Returns roster, version  or  nil, error.
function ns.ParseRosterString(text)
  local roster, version = {}, ""
  local lineNo = 0
  for raw in tostring(text or ""):gmatch("[^\r\n]+") do
    local line = trim(raw)
    lineNo = lineNo + 1
    if line ~= "" then
      local fields = { strsplit(";", line) }
      for i = 1, #fields do fields[i] = trim(fields[i]) end
      if fields[1] == ROSTER_HEADER then
        version = fields[2] or ""
      elseif fields[1]:sub(1, 1) ~= "#" then
        local p = { name = fields[1], chars = {}, charClass = {}, charRole = {} }
        local i = 2
        while fields[i] and fields[i] ~= "" do
          p.chars[#p.chars + 1] = fields[i]
          p.charClass[#p.chars] = ns.ClassToken(fields[i + 1])
          p.charRole[#p.chars] = (fields[i + 2] or ""):lower()
          i = i + 3
        end
        if p.name == "" or #p.chars == 0 then
          return nil, ("řádek %d: chybí hráč nebo postava"):format(lineNo)
        end
        p.class = p.charClass[1]
        p.role = p.charRole[1]
        roster[#roster + 1] = p
      end
    end
  end
  if #roster == 0 then return nil, "žádný hráč (čekám řádky Hráč;postava;classa;role;…)" end
  return roster, version
end

function ns.RosterToString(roster, version)
  local out = { ROSTER_HEADER .. ";" .. (version or "") }
  for _, p in ipairs(roster) do
    local parts = { p.name }
    for i, ch in ipairs(p.chars) do
      parts[#parts + 1] = ch
      parts[#parts + 1] = p.charClass[i] or ""
      parts[#parts + 1] = (p.charRole and p.charRole[i]) or ""
    end
    out[#out + 1] = table.concat(parts, ";")
  end
  return table.concat(out, "\n")
end

local function shippedRoster()
  local data = ESAttendance_RosterData
  if not data or not data.players then return nil, "" end
  local roster = {}
  for _, p in ipairs(data.players) do
    local cc, cr = {}, {}
    for i = 1, #(p.chars or {}) do
      cc[i] = ns.ClassToken(p.charClass and p.charClass[i] or p.class)
      cr[i] = ((p.charRole and p.charRole[i]) or p.role or ""):lower()
    end
    roster[#roster + 1] = { name = p.name, class = cc[1], role = cr[1], chars = p.chars or {}, charClass = cc, charRole = cr }
  end
  return roster, data.version or ""
end

--- Active roster = imported one (SavedVariables) unless the shipped file is newer.
function ns.LoadRoster()
  local shipped, shippedVer = shippedRoster()
  local imported = ESAttendanceDB.roster
  local roster, version, source
  if imported and imported.players and (not shipped or tostring(imported.version or "") >= tostring(shippedVer or "")) then
    roster, version, source = imported.players, imported.version or "", "import"
  else
    roster, version, source = shipped or {}, shippedVer, "RosterData.lua"
  end
  ns.roster, ns.rosterVersion, ns.rosterSource = roster, version, source
  wipe(ns.charToPlayer)
  for idx, p in ipairs(roster) do
    for _, ch in ipairs(p.chars) do ns.charToPlayer[ns.NormName(ch)] = idx end
  end
  ns.Fire("ROSTER")
end

function ns.ImportRoster(text)
  local roster, versionOrErr = ns.ParseRosterString(text)
  if not roster then return false, versionOrErr end
  ESAttendanceDB.roster = { players = roster, version = versionOrErr ~= "" and versionOrErr or date("%Y-%m-%d %H:%M") }
  ns.LoadRoster()
  ns.ScanGroup()
  return true, ("roster načten: %d hráčů (%s)"):format(#roster, ESAttendanceDB.roster.version)
end

function ns.ResetRoster()
  ESAttendanceDB.roster = nil
  ns.LoadRoster()
  ns.ScanGroup()
end

-- ---------------------------------------------------------------- group scan
local function groupUnits()
  local units = {}
  if IsInRaid() then
    for i = 1, GetNumGroupMembers() do units[#units + 1] = "raid" .. i end
  else
    units[1] = "player"
    for i = 1, GetNumSubgroupMembers() do units[#units + 1] = "party" .. i end
  end
  return units
end

function ns.ScanGroup()
  wipe(ns.present)
  wipe(ns.unknown)
  for _, unit in ipairs(groupUnits()) do
    local name = GetUnitName(unit, true)   -- "Name" or "Name-Realm"
    if name and name ~= UNKNOWNOBJECT then
      local idx = ns.charToPlayer[ns.NormName(name)]
      if idx then
        if not ns.present[idx] then
          ns.present[idx] = { char = name, unit = unit, online = UnitIsConnected(unit) }
        end
      else
        ns.unknown[#ns.unknown + 1] = name
      end
    end
  end
  ns.Fire("GROUP")
end

function ns.CountPresent()
  local n = 0
  for _ in pairs(ns.present) do n = n + 1 end
  return n, #ns.roster
end

-- ---------------------------------------------------------------- guild online
local lastGuildRequest = 0
function ns.RequestGuildRoster()
  if not IsInGuild() then return end
  local now = GetTime()
  if now - lastGuildRequest < GUILD_REFRESH_MIN then return end
  lastGuildRequest = now
  if C_GuildInfo and C_GuildInfo.GuildRoster then C_GuildInfo.GuildRoster() end
end

function ns.ReadGuildRoster()
  wipe(ns.guildOnline)
  if not IsInGuild() then return end
  local total = GetNumGuildMembers()
  for i = 1, (total or 0) do
    local name, _, _, _, _, _, _, _, online = GetGuildRosterInfo(i)
    if name and online then ns.guildOnline[ns.NormName(name)] = name end
  end
  ns.Fire("GUILD")
end

--- Character to invite for a player: online guild char (main first), else the main.
--- Returns name, isKnownOnline.
function ns.InviteTargetFor(idx)
  local p = ns.roster[idx]
  if not p then return nil end
  for _, ch in ipairs(p.chars) do
    local full = ns.guildOnline[ns.NormName(ch)]
    if full then return full, true end
  end
  return p.chars[1], false
end

-- ---------------------------------------------------------------- invites
local queue, ticker, waitSince, aloneSent = {}, nil, nil, 0

local function inviteUnit(name)
  if C_PartyInfo and C_PartyInfo.InviteUnit then C_PartyInfo.InviteUnit(name) else InviteUnit(name) end
end

local function convertToRaid()
  if C_PartyInfo and C_PartyInfo.ConvertToRaid then C_PartyInfo.ConvertToRaid() else ConvertToRaid() end
end

local function canInvite()
  if not IsInGroup() then return true end
  return UnitIsGroupLeader("player") or UnitIsGroupAssistant("player")
end

local function stopQueue(msg)
  if ticker then ticker:Cancel() end
  ticker, waitSince, aloneSent = nil, nil, 0
  wipe(queue)
  if msg then ns.Print(msg) end
  ns.Fire("INVITES")
end

local function tick()
  if #queue == 0 then return stopQueue("pozvánky odeslány") end
  if not canInvite() then return stopQueue("nejsi leader ani assist – nemůžu zvát") end
  if IsInRaid() then
    inviteUnit(table.remove(queue, 1))
    waitSince = nil
  elseif IsInGroup() then
    -- party formed: convert to raid, invites continue next tick
    if UnitIsGroupLeader("player") then convertToRaid() end
    waitSince = waitSince or GetTime()
    if GetTime() - waitSince > INVITE_WAIT_MAX then return stopQueue("převod na raid se nepovedl – zbytek pozvánek zrušen") end
  else
    -- alone: at most 4 pending party invites, then wait for the first accept
    if aloneSent < 4 then
      inviteUnit(table.remove(queue, 1))
      aloneSent = aloneSent + 1
      waitSince = waitSince or GetTime()
    elseif GetTime() - (waitSince or GetTime()) > INVITE_WAIT_MAX then
      return stopQueue("nikdo nepřijal pozvánku – zbytek zrušen")
    end
  end
  ns.Fire("INVITES")
end

function ns.QueuedInvites() return #queue end

function ns.InvitePlayer(idx)
  local target = ns.InviteTargetFor(idx)
  if not target then return end
  if not canInvite() then return ns.Print("nejsi leader ani assist – nemůžu zvát") end
  if IsInGroup() and not IsInRaid() and GetNumGroupMembers() >= 5 and UnitIsGroupLeader("player") then
    convertToRaid()
  end
  inviteUnit(target)
  ns.Print("pozvánka: " .. target)
end

--- Invite every roster player who is not in the group (online guild char preferred).
function ns.InviteMissing(onlyOnline)
  ns.ScanGroup()
  ns.ReadGuildRoster()
  if not canInvite() then return ns.Print("nejsi leader ani assist – nemůžu zvát") end
  local added = 0
  for idx in ipairs(ns.roster) do
    if not ns.present[idx] then
      local target, online = ns.InviteTargetFor(idx)
      if target and (online or not onlyOnline) then
        queue[#queue + 1] = target
        added = added + 1
      end
    end
  end
  if added == 0 then return ns.Print("nikdo k pozvání") end
  ns.Print(("zvu %d hráčů…"):format(added))
  aloneSent, waitSince = 0, nil
  if not ticker then ticker = C_Timer.NewTicker(INVITE_INTERVAL, tick) end
  ns.Fire("INVITES")
end

function ns.CancelInvites() stopQueue("pozvánky zrušeny") end

-- ---------------------------------------------------------------- attendance
--- Export string: ESA1|yyyy-mm-dd|HH:MM|Player=1:Char|Player=0|…|?=UnknownChar
local function buildExport(rec)
  local parts = { RECORD_HEADER, rec.date, rec.time }
  for _, p in ipairs(ns.roster) do
    local ch = rec.chars[p.name]
    parts[#parts + 1] = p.name .. "=" .. (rec.present[p.name] and "1" or "0") .. (ch and (":" .. ch) or "")
  end
  for _, name in ipairs(rec.unknown or {}) do parts[#parts + 1] = "?=" .. name end
  return table.concat(parts, "|")
end

--- Records who is in the group right now. One record per day – a second write overwrites it.
function ns.WriteAttendance()
  ns.ScanGroup()
  if #ns.roster == 0 then return nil, "roster je prázdný" end
  local rec = { date = date("%Y-%m-%d"), time = date("%H:%M"), present = {}, chars = {}, unknown = {} }
  for idx, p in ipairs(ns.roster) do
    local pr = ns.present[idx]
    rec.present[p.name] = pr and true or false
    if pr then rec.chars[p.name] = pr.char:match("^([^-]+)") or pr.char end
  end
  for _, name in ipairs(ns.unknown) do rec.unknown[#rec.unknown + 1] = name end
  rec.export = buildExport(rec)
  rec.written = time()
  ESAttendanceDB.records[rec.date] = rec
  local n, total = ns.CountPresent()
  ns.Fire("RECORD", rec)
  return rec, ("docházka %s (%s): %d/%d hráčů v raidu"):format(rec.date, rec.time, n, total)
end

function ns.RecordDates()
  local dates = {}
  for d in pairs(ESAttendanceDB.records or {}) do dates[#dates + 1] = d end
  table.sort(dates, function(a, b) return a > b end)
  return dates
end

function ns.LatestRecord()
  local dates = ns.RecordDates()
  return dates[1] and ESAttendanceDB.records[dates[1]]
end

-- ---------------------------------------------------------------- events / slash
local f = CreateFrame("Frame")
f:RegisterEvent("ADDON_LOADED")
f:RegisterEvent("PLAYER_ENTERING_WORLD")
f:RegisterEvent("GROUP_ROSTER_UPDATE")
f:RegisterEvent("GUILD_ROSTER_UPDATE")
f:RegisterEvent("UNIT_CONNECTION")
f:SetScript("OnEvent", function(_, event, arg1)
  if event == "ADDON_LOADED" then
    if arg1 ~= ADDON then return end
    ESAttendanceDB = ESAttendanceDB or {}
    ESAttendanceDB.records = ESAttendanceDB.records or {}
    ns.LoadRoster()
  elseif event == "PLAYER_ENTERING_WORLD" then
    ns.ScanGroup()
    ns.RequestGuildRoster()
  elseif event == "GROUP_ROSTER_UPDATE" or event == "UNIT_CONNECTION" then
    ns.ScanGroup()
  elseif event == "GUILD_ROSTER_UPDATE" then
    ns.ReadGuildRoster()
  end
end)

SLASH_ESATTENDANCE1 = "/esa"
SLASH_ESATTENDANCE2 = "/esattendance"
SlashCmdList.ESATTENDANCE = function(msg)
  local cmd, rest = msg:match("^(%S*)%s*(.-)$")
  cmd = (cmd or ""):lower()
  if cmd == "" or cmd == "show" then ns.Toggle()
  elseif cmd == "write" or cmd == "zapis" then
    local rec, info = ns.WriteAttendance()
    ns.Print(info)
    if rec then ns.ShowText("export", rec.export) end
  elseif cmd == "invite" or cmd == "pozvat" then ns.InviteMissing(rest == "online")
  elseif cmd == "cancel" then ns.CancelInvites()
  elseif cmd == "import" then ns.ShowText("import")
  elseif cmd == "export" then
    local rec = rest ~= "" and ESAttendanceDB.records[rest] or ns.LatestRecord()
    if rec then ns.ShowText("export", rec.export) else ns.Print("žádný záznam docházky") end
  elseif cmd == "roster" then
    if rest == "reset" then ns.ResetRoster(); ns.Print("importovaný roster smazán, platí RosterData.lua")
    else ns.ShowText("export", ns.RosterToString(ns.roster, ns.rosterVersion)) end
  elseif cmd == "list" then
    for _, d in ipairs(ns.RecordDates()) do
      local r = ESAttendanceDB.records[d]
      local n = 0
      for _, v in pairs(r.present) do if v then n = n + 1 end end
      ns.Print(("%s %s – %d přítomných"):format(d, r.time, n))
    end
  else
    ns.Print("/esa – okno | /esa write – zapsat docházku | /esa invite [online] – pozvat chybějící | /esa cancel | /esa import – vložit roster | /esa export [datum] | /esa list | /esa roster [reset]")
  end
end
