#!/usr/bin/env python3
"""Generate ESAttendance/RosterData.lua from the "Roster" tab of the guild Wishlist sheet.

    python build_roster.py             # write ESAttendance/RosterData.lua
    python build_roster.py --install   # ... and copy the addon into WoW's Interface/AddOns
    python build_roster.py --string    # print the in-game import string (/esa import) instead

The sheet is read through the public gviz CSV export (same as tools/roster/make_splits.py),
so no Google credentials are needed. Column layout: Hráč | Main char | Main classa |
Main role | Alt char | Alt classa | Alt role | Poznámka (see ROSTER_HEADER in
tools/roster/class_loot_dropdowns.gs). The WoW AddOns folder is auto-detected as
<repo>/../_retail_/Interface/AddOns; override with --wow PATH or the WOW_ADDONS env var.
"""
import argparse
import csv
import datetime as dt
import io
import os
import re
import shutil
import sys
import unicodedata
import urllib.request

WISHLIST_ID = "1CUG3oyufoNs5CrY68WMJVVHLJz-52uFQMuOtv5q3ECI"
ROSTER_URL = ("https://docs.google.com/spreadsheets/d/%s/gviz/tq?tqx=out:csv&sheet=Roster"
              % WISHLIST_ID)
HERE = os.path.dirname(os.path.abspath(__file__))
ADDON_DIR = os.path.join(HERE, "ESAttendance")
OUT_FILE = os.path.join(ADDON_DIR, "RosterData.lua")

CLASS_TOKEN = {
    "death knight": "DEATHKNIGHT", "demon hunter": "DEMONHUNTER", "druid": "DRUID",
    "evoker": "EVOKER", "hunter": "HUNTER", "mage": "MAGE", "monk": "MONK",
    "paladin": "PALADIN", "priest": "PRIEST", "rogue": "ROGUE", "shaman": "SHAMAN",
    "warlock": "WARLOCK", "warrior": "WARRIOR",
}


def norm(s):
    return re.sub(r"\s+", " ", unicodedata.normalize("NFC", str(s or "")).strip().lower())


def class_token(name):
    n = norm(name)
    if not n:
        return ""
    return CLASS_TOKEN.get(n, re.sub(r"\s+", "", n.upper()))


def load_roster():
    """-> list of {name, chars:[(char, classToken, role), ...]} in sheet order."""
    try:
        text = urllib.request.urlopen(ROSTER_URL, timeout=30).read().decode("utf-8")
    except Exception as e:  # noqa: BLE001
        sys.exit("Roster download failed (%s)." % e)
    rows = list(csv.reader(io.StringIO(text)))
    if len(rows) < 2:
        sys.exit("Roster tab is empty.")
    header = [norm(h) for h in rows[0]]

    def col(name, required=True):
        if norm(name) not in header:
            if required:
                sys.exit("Roster is missing column '%s' (found: %s)." % (name, ", ".join(rows[0])))
            return None
        return header.index(norm(name))

    ip, im, imc, imr = col("Hráč"), col("Main char"), col("Main classa"), col("Main role")
    ia, iac, iar = col("Alt char"), col("Alt classa"), col("Alt role")
    players = []
    for r in rows[1:]:
        def cell(i):
            return r[i].strip() if i is not None and i < len(r) else ""
        player, main = cell(ip), cell(im)
        if not player or not main:
            continue
        main_role = cell(imr).lower()
        chars = [(main, class_token(cell(imc)), main_role)]
        alt = cell(ia)
        if alt:
            chars.append((alt, class_token(cell(iac)), cell(iar).lower() or main_role))
        players.append({"name": player, "chars": chars})
    if not players:
        sys.exit("Roster has no players.")
    return players


def lua_str(s):
    return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"') + '"'


def to_lua(players, version):
    lines = [
        "-- Generated by addon/build_roster.py from the Roster sheet – do not edit by hand.",
        "-- Regenerate: python addon\\build_roster.py --install   (or import a string in game: /esa import)",
        "ESAttendance_RosterData = {",
        "  version = %s," % lua_str(version),
        "  players = {",
    ]
    for p in players:
        chars = ", ".join(lua_str(c[0]) for c in p["chars"])
        classes = ", ".join(lua_str(c[1]) for c in p["chars"])
        roles = ", ".join(lua_str(c[2]) for c in p["chars"])
        lines.append("    { name = %s, chars = { %s }, charClass = { %s }, charRole = { %s } },"
                     % (lua_str(p["name"]), chars, classes, roles))
    lines += ["  },", "}", ""]
    return "\n".join(lines)


def to_string(players, version):
    out = ["ESROSTER;" + version]
    for p in players:
        parts = [p["name"]]
        for ch, cls, role in p["chars"]:
            parts += [ch, cls, role]
        out.append(";".join(parts))
    return "\n".join(out)


def addons_dir(explicit):
    cands = [explicit, os.environ.get("WOW_ADDONS"),
             os.path.join(HERE, "..", "..", "_retail_", "Interface", "AddOns"),
             os.path.join(HERE, "..", "..", "..", "_retail_", "Interface", "AddOns")]
    for c in cands:
        if c and os.path.isdir(c):
            return os.path.abspath(c)
    sys.exit("WoW AddOns folder not found – pass --wow \"…\\_retail_\\Interface\\AddOns\".")


def install(target_root):
    dest = os.path.join(target_root, "ESAttendance")
    os.makedirs(dest, exist_ok=True)
    copied = []
    for fn in os.listdir(ADDON_DIR):
        if fn.endswith((".lua", ".toc", ".xml")):
            shutil.copy2(os.path.join(ADDON_DIR, fn), os.path.join(dest, fn))
            copied.append(fn)
    return dest, copied


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--install", action="store_true", help="copy the addon into Interface/AddOns after generating")
    ap.add_argument("--string", action="store_true", help="print the in-game import string instead of writing the Lua file")
    ap.add_argument("--wow", help="path to …/_retail_/Interface/AddOns")
    args = ap.parse_args()

    players = load_roster()
    version = dt.datetime.now().strftime("%Y-%m-%d %H:%M")
    if args.string:
        sys.stdout.reconfigure(encoding="utf-8")
        print(to_string(players, version))
        return
    with open(OUT_FILE, "w", encoding="utf-8", newline="\n") as f:
        f.write(to_lua(players, version))
    nchars = sum(len(p["chars"]) for p in players)
    print("Wrote %s: %d players, %d characters (version %s)." % (OUT_FILE, len(players), nchars, version))
    if args.install:
        dest, copied = install(addons_dir(args.wow))
        print("Installed to %s (%s). Type /reload in game." % (dest, ", ".join(copied)))


if __name__ == "__main__":
    main()
